encrypt_audit:
	gpg -c ad_driver.sh
	rm ad_driver.sh
decrypt_audit:
	gpg --output ad_driver.sh -d ad_driver.sh.gpg
remove_audit:
	rm ad_driver.sh
encrypt_remediate:
	gpg -c ad_remediate.sh
	rm ad_remediate.sh
decrypt_remediate:
	gpg --output ad_remediate.sh -d ad_remediate.sh.gpg
remove_remediate:
	rm ad_remediate.sh
